### ISSUE TITLE
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation

### ISSUE THREAD

**Issue by TaurusXi** [onevcat/FengNiao#13]
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
error: Invalid platform path
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
error: Invalid platform path
cp: .build/release/FengNiao: No such file or directory

**Comment by onevcat** [comment]
Please make sure you have installed the Xcode command line tool. Maybe you could try:

```
xcode-select --install
```
