### ISSUE TITLE
xcode 9 ./build.sh xcode's Dependencies file has't files

### ISSUE THREAD

**Issue by blackchena** [onevcat/FengNiao#20]
but build Path has dependencies's framework
![2017-10-27 5 02 52](https://user-images.githubusercontent.com/8891002/32096326-bc298962-bacb-11e7-99ef-1d9a3fb1e648.png)
![2017-10-27 5 03 48](https://user-images.githubusercontent.com/8891002/32096356-daa84ed2-bacb-11e7-8a94-22ef198032d4.png)

**Comment by onevcat** [comment]
Maybe you need to generate the Xcode project again under your environment again if you want to develop it in Xcode.
