### ISSUE TITLE
The README bottom video links can't play

### ISSUE THREAD

**Issue by huaqixue** [onevcat/FengNiao#22]
Hi, I was clicked the bottom video links, and then I payed the money in the Wechat to see the playback. But after payed, I still can't played the video(The error info can see the screenshot image),mobile is same. So I don't konw how to do can make see the videos. Can you help me? Thanks !

[Part1](http://m.quzhiboapp.com/?liveId=391&fromUserId=12049#!/intro/391)

![7969f8c3-9578-4621-aac1-1c3acf2e11b4](https://user-images.githubusercontent.com/31527909/34873051-875872e4-f7ce-11e7-826f-97fb6cba2444.png)

**Comment by onevcat** [comment]
@huaqixue It seems that it is an issue in the site certification. I contacted support team of the video site and they say they are trying to fix it now. So I believe you could wait for a while until this issue gets resolved in the site.

**Comment by huaqixue** [comment]
Good
