### ISSUE TITLE
dyld: Symbol not found

### ISSUE THREAD

**Issue by MaxAdamyan** [onevcat/FengNiao#31]
When trying to find unused resources using FengNiao I get this output in console
`dyld: Symbol not found: __T0s11CommandLineO9argumentsSaySSGvZ
  Referenced from: /usr/local/bin/fengniao
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/fengniao
Abort trap: 6`
I think it has something to do with Swift 4.1 and Xcode 9.3.

**Comment by onevcat** [comment]
Swift is not ABI stable yet. So you need to rebuild FengNiao after you upgrade your tool chain. Try clone the latest version and build again should solve this issue.

**Comment by MaxAdamyan** [comment]
Thanks it did the work.
Looking forward to ABI stability in Swift 5.
