### ISSUE TITLE
Swift 5 support issue

### ISSUE THREAD

**Issue by 913868456** [onevcat/FengNiao#39]
The targets “PathKit” and “CommandLineKit” contains source code developed with Swift 3.x. This version of Xcode does not support building or migrating Swift 3.x targets.

Use Xcode 10.1 to migrate the code to Swift 4.
我的Xcode 版本是 10.2.1 (10E1001), 希望有时间能兼容最新的Swift版本,非常感谢!

**Comment by onevcat** [comment]
I tried it and it seems working well under Xcode 10.2.1 and Swift 5. Did you try to build it by following the instructions?

```
> git clone https://github.com/onevcat/FengNiao.git
> cd FengNiao
> ./install.sh
```

**Comment by 913868456** [comment]
ok,Thank you
