### ISSUE TITLE
Swift 5.0 suport

### ISSUE THREAD

**Issue by MrBugDou** [onevcat/FengNiao#40]
![image](https://user-images.githubusercontent.com/12947653/57828405-f72e5f80-77dd-11e9-8a69-77bcc1ac4540.png)

喵神您好，我打开项目源码，发现无法编译通过，原因是：
CommandLineKit、CommandLinePackageDescription、PathKit
这三个库使用的时 Swift 3
![image](https://user-images.githubusercontent.com/12947653/57828538-61df9b00-77de-11e9-8162-451b01042eee.png)
导致此插件无法通过编译，希望您能帮助我解决这个问题，谢谢。
对了，我的Xcode版本yi以及macOS系统版本如下
![image](https://user-images.githubusercontent.com/12947653/57828582-8cc9ef00-77de-11e9-82fa-be8b4d0931b3.png)
![image](https://user-images.githubusercontent.com/12947653/57828599-981d1a80-77de-11e9-8413-05fffabb0083.png)

**Comment by onevcat** [comment]
Not sure why but I can build it without problem :(

![Snip20190520_3](https://user-images.githubusercontent.com/1019875/57998095-de3deb00-7b0a-11e9-86d6-672ea58e181a.png)

**Comment by onevcat** [comment]
```
swift --version
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.5.0
```

**Comment by onevcat** [comment]
The only difference I noticed that my CommandLine was resolved to 4.0.9, but yours is 4.0.4. I guess it causes the problem.

**Comment by MrBugDou** [comment]
是这样的哈，我目前电脑上安装了一个4.1的包，然后，执行这两个命令结果是不一样的
![image](https://user-images.githubusercontent.com/12947653/58003748-03832700-7b14-11e9-9b44-c64a3445e52b.png)
至于您说的CommandLine版本解析的话我应该怎么去处理一下呢？还请喵神指点

**Comment by MrBugDou** [comment]
![image](https://user-images.githubusercontent.com/12947653/58010891-ccb50d00-7b23-11e9-9deb-44eabf940544.png)
我刚刚重新安装了5.0.1，重新尝试后依然是出现了之前的错误，我在设想是否因为您的Mac之前存在缓存，因此您的电脑是可以正常编译通过的。

**Comment by onevcat** [comment]
Can you show the content of your `Package.resolved` file? The CommandLine project already changed its Swift version in [this commit](https://github.com/benoit-pereira-da-silva/CommandLine/commit/acd46be025fbeef0de047e67e23c2a4cf34d7f81). And it should be already contained in current version (4.0.9).

**Comment by MrBugDou** [comment]
非常感谢，我在重新下载代码以后，安装成功了，谢谢喵神。
