### ISSUE TITLE
Doesn't work no macOS 10.15

### ISSUE THREAD

**Issue by erema** [onevcat/FengNiao#42]
In terminal I have the message "This copy of libswiftCore.dylib requires an OS version prior to 10.14.4."

**Comment by onevcat** [comment]
I am not sure but maybe you need this: https://support.apple.com/kb/DL1998

**Comment by lazarevzubov** [comment]
Today installed successfully on macOS Catalina (10.15).

**Comment by nfgrilo** [comment]
I was able to fix this by:
1. Make sure you have Xcode 11 installed on macOS Calatina
2. Make sure you're using Xcode 11 command line tools if you have multiple Xcode installed, with (replace by the Xcode 11 path):
  `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
    (you can check with `xcode-select -p`)

**Comment by onevcat** [comment]
I think it is not a FengNiao related issue so I am closing it.
