### ISSUE TITLE
Doesn't delete files from Copy Bundle Resources

### ISSUE THREAD

**Issue by lazarevzubov** [onevcat/FengNiao#47]
I have plenty PNG-files just as files included in Bundle. Tool successfully deleted unused ones, but records in target's Copy Bundle Resources stayed untouched. I had to delete them manually to make the project built.

**Comment by onevcat** [comment]
I prefer not modifying the xcode project file during the FengNiao process. It may cause some unexpected behavior when you run it as in build script phase in Xcode. FengNiao will only manipulate the disk file system to remove files. All other references in your bundle or target are kept no touch.
