### ISSUE TITLE
MacOS App

### ISSUE THREAD

**Issue by ldakhoa** [onevcat/FengNiao#74]
Hey, this looks great. 

I'm using this within my company app, but some images will used within API responses.
What I see now is FengNiao has three options `list`, `delete`, and `ignore`. I need to delete individual files within this tool but cannot, I have to find the file in `xcassets` and then compare it is right file and delete it manually, this seems hard because the app uses a lot of image resources (more than 30 MB).
So, I want to make a macOS app to visualize unused images and the ability to delete individual files. What do you think? I can PR to your repo.

**Comment by ldakhoa** [comment]
I have made a macOS here https://github.com/ldakhoa/ResourcePurgeX using FengNiaoKit

**Comment by onevcat** [comment]
The app looks pretty nice! Congrats!

> So, I want to make a macOS app to visualize unused images and the ability to delete individual files. What do you think? I can PR to your repo.

I hardly have time to adding new features for now to this repo. So if you want, any PRs are warmly welcome!

**Comment by onevcat** [comment]
@ldakhoa 

Merged! Great work and big thanks!

I will later add some description to the README file. And I also want to invite you as the collaborator of this repo too. Do you mind it?

**Comment by ldakhoa** [comment]
@onevcat

Nice, thank you a lot!

> And I also want to invite you as the collaborator of this repo too. Do you mind it?

That's awesome! Please feel free to add me as a collaborator to the repository, I really enjoy it.
